-- Practical 3 
--testing
SELECT
  *
FROM
  "PRACTICAL3"."SHOPPING"."NULL_FUNCTIONS"
LIMIT
  10;


-- 1. Find all records where SIZE is missing and PURCHASE_AMOUNT > 50
SELECT 
    CUSTOMER_ID, 
    SIZE, 
    PURCHASE_AMOUNT, 
    ITEM_PURCHASED
FROM PRACTICAL3.SHOPPING.NULL_FUNCTIONS
WHERE SIZE IS NULL 
  AND PURCHASE_AMOUNT > 50;


 
-- 2. Total purchases grouped by SEASON, treating NULL as 'Unknown Season'
SELECT 
    COALESCE(SEASON, 'Unknown Season') AS SEASON,
    COUNT(*) AS TOTAL_PURCHASES
FROM PRACTICAL3.SHOPPING.NULL_FUNCTIONS
GROUP BY COALESCE(SEASON, 'Unknown Season');


-- 3. Count customers per PAYMENT_METHOD, NULL -> 'Not Provided'
SELECT 
    COALESCE(PAYMENT_METHOD, 'Not Provided') AS PAYMENT_METHOD,
    COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMER_COUNT
FROM PRACTICAL3.SHOPPING.NULL_FUNCTIONS
GROUP BY COALESCE(PAYMENT_METHOD, 'Not Provided');



--4. Customers with NULL PROMO_CODE_USED and REVIEW_RATING < 3
SELECT 
    CUSTOMER_ID, 
    PROMO_CODE_USED, 
    REVIEW_RATING, 
    ITEM_PURCHASED
FROM PRACTICAL3.SHOPPING.NULL_FUNCTIONS
WHERE PROMO_CODE_USED IS NULL 
  AND REVIEW_RATING < 3.0;


 
--5. Average PURCHASE_AMOUNT by SHIPPING_TYPE, treating NULLs as 0
SELECT 
    SHIPPING_TYPE,
    AVG(COALESCE(PURCHASE_AMOUNT, 0)) AS AVERAGE_PURCHASE_AMOUNT
FROM PRACTICAL3.SHOPPING.NULL_FUNCTIONS
GROUP BY SHIPPING_TYPE;



---6. Purchases per LOCATION with >5 purchases and no NULL PAYMENT_METHOD
SELECT 
    LOCATION,
    COUNT(*) AS TOTAL_PURCHASES
FROM PRACTICAL3.SHOPPING.NULL_FUNCTIONS
WHERE PAYMENT_METHOD IS NOT NULL
GROUP BY LOCATION
HAVING COUNT(*) > 5;



--7SPENDER_CATEGORY classification
SELECT 
    CUSTOMER_ID,
    COALESCE(PURCHASE_AMOUNT, 0) AS PURCHASE_AMOUNT,
    CASE 
        WHEN COALESCE(PURCHASE_AMOUNT, 0) > 80 THEN 'High'
        WHEN COALESCE(PURCHASE_AMOUNT, 0) BETWEEN 50 AND 80 THEN 'Medium'
        ELSE 'Low'
    END AS SPENDER_CATEGORY
FROM PRACTICAL3.SHOPPING.NULL_FUNCTIONS;



--8. Customers with NULL PREVIOUS_PURCHASES but non-NULL COLOR
SELECT 
    CUSTOMER_ID, 
    COLOR, 
    PREVIOUS_PURCHASES
FROM PRACTICAL3.SHOPPING.NULL_FUNCTIONS
WHERE PREVIOUS_PURCHASES IS NULL 
  AND COLOR IS NOT NULL;



--9. Total spent per FREQUENCY_OF_PURCHASES, NULL -> 'Unknown'
SELECT 
    COALESCE(FREQUENCY_OF_PURCHASES, 'Unknown') AS FREQUENCY_OF_PURCHASES,
    SUM(COALESCE(PURCHASE_AMOUNT, 0)) AS TOTAL_PURCHASE_AMOUNT
FROM PRACTICAL3.SHOPPING.NULL_FUNCTIONS
GROUP BY COALESCE(FREQUENCY_OF_PURCHASES, 'Unknown');



--10. CATEGORY counts excluding NULL
SELECT 
    CATEGORY,
    COUNT(*) AS TOTAL_PURCHASES
FROM PRACTICAL3.SHOPPING.NULL_FUNCTIONS
WHERE CATEGORY IS NOT NULL
GROUP BY CATEGORY;



--11. Top 5 LOCATIONS by total PURCHASE_AMOUNT, NULLs in amount = 0
SELECT 
    LOCATION,
    SUM(COALESCE(PURCHASE_AMOUNT, 0)) AS TOTAL_PURCHASE_AMOUNT
FROM PRACTICAL3.SHOPPING.NULL_FUNCTIONS
GROUP BY LOCATION
ORDER BY TOTAL_PURCHASE_AMOUNT DESC
LIMIT 5;



--12. Count of NULL COLOR per GENDER and SIZE
SELECT 
    GENDER,
    SIZE,
    COUNT_IF(COLOR IS NULL) AS NULL_COLOR_COUNT
FROM PRACTICAL3.SHOPPING.NULL_FUNCTIONS
GROUP BY GENDER, SIZE;



--13. ITEMS with more than 3 NULL SHIPPING_TYPE purchases
SELECT 
    ITEM_PURCHASED,
    COUNT_IF(SHIPPING_TYPE IS NULL) AS NULL_SHIPPING_TYPE_COUNT
FROM PRACTICAL3.SHOPPING.NULL_FUNCTIONS
GROUP BY ITEM_PURCHASED
HAVING COUNT_IF(SHIPPING_TYPE IS NULL) > 3;



--14. Count of NULL REVIEW_RATING per PAYMENT_METHOD
SELECT 
    PAYMENT_METHOD,
    COUNT_IF(REVIEW_RATING IS NULL) AS MISSING_REVIEW_RATING_COUNT
FROM PRACTICAL3.SHOPPING.NULL_FUNCTIONS
GROUP BY PAYMENT_METHOD;



--15. Average REVIEW_RATING per CATEGORY (NULL->0), only avg > 3.5
SELECT 
    CATEGORY,
    AVG(COALESCE(REVIEW_RATING, 0)) AS AVERAGE_REVIEW_RATING
FROM PRACTICAL3.SHOPPING.NULL_FUNCTIONS
GROUP BY CATEGORY
HAVING AVG(COALESCE(REVIEW_RATING, 0)) > 3.5;



--16. Colors missing (NULL) in ≥2 rows and average AGE of those rows
SELECT 
    COLOR,
    AVG(AGE) AS AVERAGE_AGE
FROM PRACTICAL3.SHOPPING.NULL_FUNCTIONS
WHERE COLOR IS NULL
GROUP BY COLOR
HAVING COUNT(*) >= 2;



--17. DELIVERY_SPEED classification + customer counts
SELECT 
    CASE 
        WHEN SHIPPING_TYPE IN ('Express', 'Next Day Air') THEN 'Fast'
        WHEN SHIPPING_TYPE = 'Standard' THEN 'Slow'
        ELSE 'Other'
    END AS DELIVERY_SPEED,
    COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMER_COUNT
FROM PRACTICAL3.SHOPPING.NULL_FUNCTIONS
GROUP BY CASE 
        WHEN SHIPPING_TYPE IN ('Express', 'Next Day Air') THEN 'Fast'
        WHEN SHIPPING_TYPE = 'Standard' THEN 'Slow'
        ELSE 'Other'
    END;


    
--18. Customers with NULL PURCHASE_AMOUNT but PROMO_CODE_USED = 'Yes'
SELECT 
    CUSTOMER_ID, 
    PURCHASE_AMOUNT, 
    PROMO_CODE_USED
FROM PRACTICAL3.SHOPPING.NULL_FUNCTIONS
WHERE PURCHASE_AMOUNT IS NULL 
  AND PROMO_CODE_USED = 'Yes';



--19. Max PREVIOUS_PURCHASES per LOCATION (NULL->0), avg rating > 4.0
SELECT 
    LOCATION,
    MAX(COALESCE(PREVIOUS_PURCHASES, 0)) AS MAX_PREVIOUS_PURCHASES,
    AVG(REVIEW_RATING) AS AVERAGE_REVIEW_RATING
FROM PRACTICAL3.SHOPPING.NULL_FUNCTIONS
GROUP BY LOCATION
HAVING AVG(REVIEW_RATING) > 4.0;



--20. Customers with NULL SHIPPING_TYPE and PURCHASE_AMOUNT between 30–70
SELECT 
    CUSTOMER_ID, 
    SHIPPING_TYPE, 
    PURCHASE_AMOUNT, 
    ITEM_PURCHASED
FROM PRACTICAL3.SHOPPING.NULL_FUNCTIONS
WHERE SHIPPING_TYPE IS NULL 
  AND PURCHASE_AMOUNT BETWEEN 30 AND 70;
